name: CI

on:
  push:
    branches:
      - action-exampls
  pull_request:
    branches:
      - action-exampls
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo something
      run: echo "Hello, GitHub Actions!"

    - name: Echo something else
      run: echo "Hello, GitHub Actions!"

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Building the project..."